<?php

/**
 * @file
 * Contains rwanda.module.
 */

use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\media\MediaInterface;
use Spatie\PdfToText\Pdf;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_help().
 */
function rwanda_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rwanda module.
    case 'help.page.rwanda':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom behaviors for Aegius') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rwanda_theme() {
  $themes['rwanda_court'] = ['render element' => 'form'];
  $themes['rwanda_login'] = ['render element' => 'form'];
  return $themes;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function rwanda_form_registration_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#title'] = t('Register');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function rwanda_form_node_registrant_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $current_path = \Drupal::service('path.current')->getPath();
  $parts = explode('/', $current_path);

  $path = Url::fromRoute('rwanda.registration_form_edit',
    ['node' => $parts[2]])->toString();
  $response = new RedirectResponse($path);
  $response->send();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function rwanda_form_node_court_case_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $path = Url::fromRoute('rwanda.court_case')->toString();
  $response = new RedirectResponse($path);
  $response->send();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function rwanda_form_node_court_case_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $current_path = \Drupal::service('path.current')->getPath();
  $parts = explode('/', $current_path);
  $path = Url::fromRoute('rwanda.court_case.edit',
    ['node' => $parts[2]])->toString();
  $response = new RedirectResponse($path);
  $response->send();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function rwanda_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#theme'] = 'rwanda_login';
}

/**
 * Implements hook_form_alter().
 */
function rwanda_form_alter(array &$form, FormStateInterface $form_state, $form_id) {

  if ($form_id === 'node_court_case_form') {
    // Unimplemented.
  }
}

/**
 * Implements hook_field_widget_entity_reference_paragraphs_form_alter().
 */
function rwanda_field_widget_entity_reference_paragraphs_form_alter(&$element, &$form_state, $context) {
  if (isset($element['#paragraph_type']) && $element['#paragraph_type'] != 'accomplices') {
    return;
  }
  $configs = [
    [
      'field_name' => 'field_restitution',
      'conditions' => ["value" => 'guilty'],
      'controlling_field' => 'field_court_decision',
    ],
    [
      'field_name' => 'field_accomplice_sentence',
      'conditions' => ["value" => 'guilty'],
      'controlling_field' => 'field_court_decision',
    ],
    [
      'field_name' => 'field_tig',
      'conditions' => ["value" => 'guilty'],
      'controlling_field' => 'field_court_decision',
    ],
  ];
  foreach ($configs as $config) {
    paragraph_field_state($element, $config['field_name'], $config['controlling_field'], 'enabled', $config['conditions']);
  }
}

/**
 * Utility Function to add states to Paragraphs.
 *
 * @param array $element
 *   The element being receiving State restrictions.
 * @param string $field_name
 *   The field who's parameters are changed.
 * @param string $controlling_field_name
 *   The field whose state affects the field.
 * @param string $state_key
 *   The selected state.
 * @param array $conditions
 *   The conditions to be met.
 */
function paragraph_field_state(array &$element, $field_name, $controlling_field_name, $state_key, array $conditions) {
  if (!isset($element['subform'][$field_name])) {
    return;
  }
  $subform = &$element['subform'];
  $parents = $subform['#parents'];
  $parents[] = $controlling_field_name;
  $field_id = array_shift($parents);
  $field_id .= '[' . implode('][', $parents) . ']';
  $subform[$field_name]['#states'][$state_key][':input[name="' . $field_id . '"]'] = $conditions;

}

/**
 * Implements hook_media_presave().
 */
function rwanda_media_presave(MediaInterface $media) {
  if ($media->bundle() != 'document') {
    return;
  }
  $text = FALSE;
  if (!$text) {
    $file_id = $media->get('field_media_document')->getValue()[0]['target_id'];
    if ($file_id) {
      $file = File::load($file_id);
      if ($file) {
        $data = file_get_contents($file->getFileUri());
        $location = 'temporary://myfile';
        $tmp_file = file_save_data($data, $location, FileSystemInterface::EXISTS_REPLACE);
        $tmp_uri = $tmp_file->getFileUri();
        $stream_wrapper_manager = \Drupal::service('stream_wrapper_manager')
          ->getViaUri($tmp_uri);
        if ($file->getMimeType() == 'application/pdf') {
          $file_path = $stream_wrapper_manager->realpath();
          $text = Pdf::getText($file_path);
          $tmp_file->delete();
          if (preg_match('/IFISHI/', $text)) {
            $terms = \Drupal::entityTypeManager()
              ->getStorage('taxonomy_term')
              ->loadByProperties(['name' => 'Charge Sheet']);
            $tid = key($terms);
          }
          if ($tid) {
            $media->set('field_document_type', ['target_id' => $tid]);
          }
        }
      }
    }
    else {
      \Drupal::logger('islandora_text_extraction')
        ->warning("No file associated with media entity.");
    }
  }
}
